# Generated by Django 3.2.3 on 2021-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('bId', models.AutoField(primary_key=True, serialize=False)),
                ('bHeadline', models.CharField(max_length=100)),
                ('bBody', models.TextField()),
                ('bPic', models.ImageField(upload_to='blogs/')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nHeadline', models.CharField(max_length=100)),
                ('nBody', models.TextField()),
                ('nPic', models.ImageField(upload_to='news/')),
            ],
        ),
    ]
